---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: sigtech
spec:
  encryptedData:
    MYSQL_DATABASE: AgDHO+HCDfCKE1fLl3YkPTzHmWp/VM/8MxHiYe4uJe5dl45jDak2/wvMv4kJSzhLY1rLuneSOFle3BKaCV8C1+dAZY4+lJQ4mIOiZFuIhcm94ELlf1Il8BmwYkbx9RpCXxIgtBtECl5DtHUwZMA0aCpiDIqoLBLOlqjnmBywIlJgP2zirTJWb+J+Z17CEktAiuLcvq/SrJdYB2f7qjh/sYcdFtsKLtir8HFLR1GP//g8E0U8T5shG5uQyWqdooqqR4UVkNEsvjkFnrXgX3U/vdsqLbyJvLdwtPcV6LJ6kpUj7hjpBhoEHsZOe+tWqDgIz7kmrjXiO22/h2CIoTfNGgELVUiYaBFg40AOXlGukLyZ+DnLBxrwlsmuxY6Nm4GY8OP5JVYgxPy4n2Fu0mybEH/0RabjG8rwbJsCroNgTvSx0LaGeC6Ok1zumjKMgBMPRsf5l/JQq7cOsrsiRTWcaP1npUKs1aT7Y/5tXJQAgU1EjWvO3fI9nFTWCF9mQq1tTkv/BheH49lW7Womzi5R5D31GaDZ5BvRwIUJhvasScVefuxDjb9qKyQCQO0Bw2A4R8qjnJzzuIwpncFbjPgn+rGR7JumKhim6uKuVb8NA6ozc84ZEnuI9Mf+hyL4Hw2a9AaL89mL8Rmt4fUn7xlzTs7CvqZVWRA5KvSfTiMv3T2DGpcXZUGj43VfvDWKYlZRZa0GwD9Ia54J1pa3C/lp
    MYSQL_ROOT_PASSWORD: AgBDs+wwKMqF90yXfRdGNFH5oOFpBcWupmMBnAOXT+TsF/fMoft7OH9+i1thnJk6DqI5Shd7a5BqEDgWt0z2Q8kJzRU8Ym/nrl8Q5cxuADMe5jHKzawmt3gZtcNbfgORS1vhDGE45KTNV5RNdjxetH6g36bsp2jIcH4gqix4YmLPpgeXMbgmfgAUG/MHqid7KgRKHJCb4ehLbmMENpONlXDanrzfrX3lcy64MLxu+7rtnUZE1x/CTvoQwD5OOCG6Gvvjrs88tmedTKQMgeLSPV5w6VZ08NwSoi2/8E1pmviobe+MEa2msgKVrA8ltoFqxgL1d+bzty9rjwiZXQDxjZ+ooZmWO2TPAaaUSWjP0VvSpVDWGvTCN4qnW+DJsoF2nSpW+0eC6OIIzVppP2b7u423IWSJyuIdD8xYGwGdd5E9pHpApIYkAfnr35xcSEGAtc5xTKnaVugQ+sNmMVZkm+5a8qET5hVg5lgZYW+bJcqBzrPzHS9Ionte1zSzsh7OQt2FshBZcCPhJRyyXGACvFPtQUFmPsAc/Rt3skPOTEzliAD6ZQXXtI3VTShGDz4KEprvECVzSG7B3Zy6rRD+R6XuLAmNNYLi54E7wBmSTIbao503K9i31/N4JBhTufUiHlDcPhIsGzEgSBO5rmtoTzpS94nJeESzkSaptJoboQ7LjOgVcGAK6kGTbWVNETCkZIZRs4wcFWr53gRV6WQ=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: sigtech
    type: Opaque
