---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_DATABASE: AgBMPSPG6qpgwwf4Wi1LTfpBToSP5I63NjBVL536Fou0ZeMZ+ymmXsKLzVxChSLdXo5ML9vKWlEZ8+sS075MTEhtLI6CA5NV/mNVyycHxPU0XVxEzlCjFZj7IQNmLAkXpcGn3Opl2bB/cQ670yrzJ9K8qJUz6shj3JJoZuUj5rjncxuWSqa1NOn67Z2bawxSx6TnVeOzWvc2s7ygUJ9ZfH1Im6QO4o6fbHitpS5lrvhpFxpYr/j46T2HpaBWZsziDnJ9+f/9tJKhslIHIai5WCixDuI8U1b19LnyrBdhPaSZ/wD0XxsSvcuPmbAJ21mgG9TDR5W8JI4YAWV1TMH3qKou3UpckQ1HrcblUtvt/vyuM/44YMYc+gCKIdJhhaLiETct2EnAb8zCtWygv41Nzcgr6DWq1PckgUOExGcekm3PbqRKtQXU8jOUpR5XnpTaKEd1DMcQfEYFSYUJmWtK5YjWp7GptAh4eJSHMY2BZS6OFWZWpdiDuXItsDK+HFD1Aoiu6AHdhtvPYsrb8HQGwbuYjH3H1WSTTHVMWGvUAr6KRNsd8jRd3+0ZkIlhMMYSIDoswJMeVRaFV0Ixu3+p2LOzo/ul2IcZRKFTM5JjZDdW+kaxc/XW3JWeaX7+HTfoc4+MJAbatoafTA6K/DAzqa9FrRZlOMPT4DESmnk0VHPgbyMqh9TxtLy4/U6C8bdImBhpDqTAGQ9O6gtEd1NW
    MYSQL_ROOT_PASSWORD: AgBRBbbHxybSdD8hGFsz+pCpb8o+6LyszcfhQkxaAbsAlb0PTC4VsPfvLMj1DlH7EQV2IPJMo4wgO3jh1S6MpbGDBjonjI4RP9HLodCN3v4egk7pVSfY0rCsK0fneIO4slhzNp8enPTQWm6QiDaCk4knWYWMD61WN3iA8CXyL8rEbsISHqm0aeOExy9SZ+le3WSQ5gKIezicQx58yoDm65BdWwExuA6PC0FuUKnF4lPRUhpLGg/J2bA3CkaTxkgf8Fl9onz8qbPY80IKmnUOBIt2eCGqESBkRFQptd+2UESanR4o6kp/jMeBPNrsR+Xma7kCzqmpsKgwGRFkmxTxzt3z9JPcu8k08lkqIehVPmW2KuKvPMfKYnGv3xSQdLj6yKQrbqN95xEq8cquuWjW/tHuTOydc8YJzs4Yu15grZFRoUqL87AS29BObeonR9a4zHJ24tpfwv2TsnGal6TjQAvO085OSPlktolxEw0FkTT02kb1rITkABgeu7Rz9HsPio/fI5/XGScnV/MI6PzpkUm/yDAXteNNXVGW6S8R+vl7FPRe5JQLT9tBK98ei+Bd/5o48q/D1QTzBeT8TtWeeG4igpzOuiXTt7FWgwtM16kvn/ftN90OSmEvQjllO4QEVXOpnCsE1A6UPOyKCcHjVqES6fzba04IJUi+DXFbMOF8lWom6EKvPXbzwgoNlPHuRSG4t16s6cn5ex/Qc3g=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: default
    type: Opaque
