---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_DATABASE: AgBZF38Q9A+eO2gBmfBWaMpykgcMqWqVfvhc1zu2Blcn/Qpt88ds36uYTQZ/+wEXBnDl8TN2hhargMcLbCOHZUDdmXOIu8GKDag0wtHRyKbdHXF6S3gpJFhwH6W2+We7F1Au3MGSN9qZWWAfYdzO/eVbW4/IfA8Vdtxdv+rzVIH7iWx4c7CKDColTkAqj2rksSwv5R4TA+DNDejJXREWPxIFPL3VtCSWJ6gQp51Qw5DKVYTutbGedMQuvuAA3JJTw7knzE0gv46SECKO2NMNhdPBqq72/E1+Yd3LHxkMU9a5R/QabKc+dEYGdatbRTkyCX4I+3/cArhwLDhuVEaO4ADjeSH3CEftfKaeDEQjY9gDiHbTBu/nV4LPUwTaAxfV/xykoz8BhZdKIS7rPiVqyewPyZCN76MMc6GxdhLhE1u7h9hHNzhqX8FpM4XX/2VU8vDA1bByTqLx71098Ls0MlcAwbBncBplxGZjFzt3Wwi6ef6zMtvtarWhrutTh6wgeAje4pQS4bZNTWdgOQQqAQZXZtcaLnSqJDbFXyiDqh7y8D6vMTT1fW7uL2E9rCi1q5uEEWzi8rqOeTiq1RC43nP+GK4C9TmU9f7AH8U3dj/ZVgFQBUELy+F3hsYa+I85y7gbpuZEa4I3hIewnxfDH04eg5Qfcmg1XAkb/VcxsBuNYT6XzZ00NBEl7ioiCH6gywHIHBc5hX6eR6GirFEq
    MYSQL_ROOT_PASSWORD: AgCoFAEE82LFrDuc1br/WlANIB2pYHg6c0A2QTUEJnHHrFHfFL8m3h9Nmm5ncGj9Ys+H3Q0SCJ9wKn3xrMxznTHUHnzNCBLj9gc7cxJKI+rvgvQFx91MPmD4DKZ3wzDEsTA0/taZAXTjOQzv2uSPeY79hCMDX5zKrg8IAZMZlTtd4vnj2upjrXZTxgUhp27MdBk3dy4yYx3eT+w5I7ysKXfvxm+T/0wR7ALl9cywWq+JamRaUVzMYmJtkf2sxtYRZNQuEB2oOuWLZ5/bx+LPooDMiuxfIdKeUsVByUZUTYILfnI9M+8uYeHQ9vF9DH7wl9rD6yIKrUKMbUAlGt4c1HQBuVXr9fX8eCRztpPKJqDU2sYeMaJfe4c5zBzvmg+Q8Hf++BpCcPdaAj1HeC9av1lf5Byvqyl6Oea/q468M0KQESH1RCt/hpast8FAXcfhM/pih52slp2CiVA05vYeBXJ4vpbsPRgNrASfnA61LAZT9hlDH9OuJ+pVTq+sbyYMN0W+yKpd0x/oMaljHyZ1B+kwN6mMKthZ3pA+KKThV59mLLCTicwwt3EOejB20ulJocPxN6vqnj+HFJ+QlGALQD/o+7qM28QRyRZXlWLCOuoI57qphL+vkO0bYQtM7qf7HbhAADj+Eon5AgrD1nmcyH3WnTn6vS7f8apVBiIoyDCRm+9U693D5uAl4BS4Fiz66pE5bEAZQ9RcvB6YsaY=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: default
    type: Opaque
