---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_DATABASE: AgA+IEku3dd4wJ2Ujj1vXj6puc2JyQVoG87ViIdHg47qaip9Od/FK1DjRbCSviiv2hpvCW+Q580rcblfh1ZLyn8gAt7aeNw1jmJq4z6TEgWQ/YFBtte5BiAAiO4ShKAtd53oVDfSI9AcAJO37RTf3tZt4oqiCqO5gK94ir6wZflXx+hOazpt9C3KS8/IeBlKgQL4k6kYSCuEmpQ+AS1ThaPgCe74ddUoHuULilwUAHA6N43xDAtPFn8Cmh33vR7dBTv86oMlJ7DDSjksJvDxZJMKjSPlLMZGljwaXJmqU2Dq4R/66Ja3IbWzpdq+GLQbW33HoMHywAm96JGgHNouxXGhsBqG07lQb1E5A3cOXQAMQ9b2xALLjKU90+GKE6MyfQ9L6NJycR6NqKEG/oTzMG33isGyeJ5i4mXwskE4WkCKCy94TtWhHHXIZWUu+r7yhlGfTiBwZzDnMhFjLnSyYl0uFvQ1zQPRv0ugxTj9+tj6oxaVVF6PyZS4sf0cOMtn+5tMWvWiAKuQHX3+ZljYpUqH8sJmJgvP+GpIdaahtda9p1SRlQD+MA2QcTmtebF7OdJxc0Evm+20d9MGchmBn+5PJThzN6W3ZmUvDAzFtQJNHHNT/gEudEtAm4zOTEI0Ky6tJdig0xLCzZGVlLh1Ye9KHJgdmv3QxkhFGklGJJ2ZVEFLqaHDZMmxf6nnAJgu2IfP9qgqD+oHZEAFnIaw
    MYSQL_ROOT_PASSWORD: AgB+sf2T98ZvlhxEbCVLGAeg2cVqe9+sqBsSvCa6Cn5N1NPF2mi6yBwG6ZUfziFQEylg1f2CeY8n+jdduaJcTGLA3OY8TLPvlkYvFmPHI6xv9kxoyua5hAEyALHIbrom0Ra1yX5xmyhEfyWSxmoVyNq9pvnJvdXjpTqJNaSdb7cLH//G066Q5tCztqDm0WmDaNKux22kqNW+1EYOtiq7ZPiZtYe17Dj4tEw85DeT/AtT5DwPv4rFXeK34my3qJ9Y0s17qVsOwTleqbasf6wJsYhz8iITBu6nvHRtCE6DqxNsvS8qGLzbWd09LoviPFRxPNuJVPlIsBoVAmM1g+CWiapE+eRiCnPqC8mT768vCfRkZv88bn2Z/6w/lkXC9asFyU7ZpkfcTAc642CQkzj2QYo+s5nHf6PTaN3Ymzr53Qo2BN+O5bFj1Z5r5ysvKA4SIw3Q7996gK3jo0fwNpHNzP6y6b02yttCEE2QcbgZwpTiKRqvHi0tQsXwXZm1WXYYQ6HhwA2xi+WhotTy3MUap+4Tuuq2gKDaMqhkcLH9pmpvuHfGfcD/MqdHsRnNO29qhBzTyHoQC3RJptLOAAVAdWPyS0XD3gpH4v7hHxucWDWm3Does2q9YEzd1YzsPMEghpDgkggG0uVCASx6HdyK9g5qXHiJ3w1Pt5aKqhPc+0S7+8uFYCS6jWFPpx3b7B6cm4wZPWZ4kqoUrycdHPo=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: sigtech
    type: Opaque
