---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: sigtech
spec:
  encryptedData:
    MYSQL_DATABASE: AgCorvcMT7EcgXa9gWKLReFXrrUASC+7X9bavGjaRnwMdvHQtFfkk/fze+d26ZtLJTO+ByI2bfMzTb8WyVNTFuPLYVSjFj0O8KF2R4IZovgz38sA+LWehv/0j8ZA0jCodLp8v4cLUdBD6BBeGa33TSAH9PQ7l5COMhJcB4FoGhm15UkCqj7+9M/Tn3/LRHf8qwe4Fy+ErHi4qT6IpRnVO0P95Tw+y57lx3tI8tuhYfagaa83bKW9speC//o0XDqUnMQJa8cF1OP2Wk5UVo7jJe4V1gUZcYh62RhuQJVMH6YC1trweuYHsGFLmibMbkv9mc+ov5WhiB0Ka/wH6HvzfktS6gIgNe3bYzl8SNCAl5u08+OMSgtJF74Oow95nPzIpRFs9XjmV9f07yaGwkkOVIzaTFNT/I69ac0r+SoimsHYvHoaKYy3laMQD9eA23kATdN1SIVGFSui6w57dNfGT0SGedXOhPPye0zkSSm0fWOBhSVlO+1D0gJfJ4byJV9CNgHFrvQO/NJ1IKqgYLyFgMN4idZxxbiJypLbaUu8iWRNKAXoSLZZX04jqW/fXnsGYhRuCGoP9LkCVUgvPfbET2yB4IcEBqDXCetFoqlTNCn2XZU4+WEY8+wwzYzmuAStpFOYcO3iEGZPN51a6/5S5FFaMJYTqMoKyd4zjoHVUJL56VHvoju4Ih9F5ISuX4pRxnPgEkYKOEk862GYjK3x
    MYSQL_ROOT_PASSWORD: AgB6lacGMMNbZi1LwzmEDy/46rgWnhFzu9FxsgGd2njHPCIGaUR2c79VhmKttHjoZ5o51WLjZzLxkjToi+x7bLa4MgRpbhNnDxYzFPlnvXBn6cYibyGGZq6Ko/Om5gVqSNMwrdOufFSZ4TN+ioP+FeaJWpLpEjiL5MLPFKT0RMkzTlWMk7yssHmuV716tYJvyz35Q4J4ApN/HSH2SFkg3VDO/dBUIYMjJ2JVDqGnpD/mVg19KLxFjpGeU/HoK2PfgAWjYyOt4xN321d4NoZ1Nus9BI6+VWhaZ8F58IV1MSRb1uTGC+K1qu9TSWBi7hSZSInRB0S+uLfRZWTfvRBLNed7UbU8M4WcPW3fchROumRoyI5Q0J/6FxEtFceWiyJbOl4zpPnd2LYRdaRq5WGwlhT/woSWoYRAwOdL2VDcrUhfckSS/7X+44PBG/kItHDVc/O+d6VvYu/pSRSTPU50pN2glUemQmXzDPGu446VKL2+0OoDLTPp5kwaBC2F3o/LMQUTvGuYQMiAC0E7q4AUNXrzm6/2adBpYhjNn6X1xhC79ahD6dnfTjkQX4sxCdw1FwryKgSC6IqAbogdAwSyP0b0NYV8p/hVCeJcaho0ZG3y2esJ9OHVK4BY2/3r1Wl3hsGewbqi00uYSWbyt9s9xxxMVZFsuf9kq0sGrE0KWa9X6WshHxPjwo4VMKUgyYeu0YZbpmltJTMHqAO5uNo=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: sigtech
    type: Opaque
