apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pythonApp.serviceName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.pythonApp.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.pythonApp.servicePort }}
      targetPort: {{ .Values.pythonApp.containerPort }}
