apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlService.name }}
spec:
  ports:
  - port: {{ .Values.mysql.servicePort }}
  selector:
    app: {{ .Values.mysqlService.name }}
  clusterIP: {{ .Values.mysql.clusterIP }}
