apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.mysql.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    MYSQL_DATABASE: {{ .Values.mysql.encryptedDatabaseName }}
    MYSQL_ROOT_PASSWORD: {{ .Values.mysql.encryptedRootPassword }}
