apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlService.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.mysqlService.name }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
