apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mysqlService.name }}
spec:
  serviceName: {{ .Values.mysqlService.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysqlService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysqlService.name }}
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
          - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.secretName }}
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.secretName }}
              key: MYSQL_DATABASE
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql

  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.mysql.storageSize }}
