apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mysqlService.name }}
  labels:
    app: {{ .Values.mysqlService.name }}
spec:
  serviceName: {{ .Values.mysqlService.name }}   # Service managing this StatefulSet
  replicas: 1                                    # Set replicas as needed
  selector:
    matchLabels:
      app: {{ .Values.mysqlService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysqlService.name }}
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.secretName }}
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.dbName }}
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql          # MySQL data directory
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.mysql.storageSize }}  # e.g., 10Gi
