name: Lint Kubernetes Manifests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

       # Install kubescape for validation
      - name: Install kubescape
        run: |
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | bash

      # Validate manifests
      - name: Run Kubescape validation
        run: |
          kubescape scan --submit --file-path ./k8s/*.yml
