name: Lint Kubernetes Manifests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install kube-score
      - name: Install kube-score
        run: |
          wget https://github.com/zegl/kube-score/releases/download/v1.13.0/kube-score_1.13.0_linux_amd64.tar.gz
          tar xf kube-score_1.13.0_linux_amd64.tar.gz
          sudo mv kube-score /usr/local/bin/

      # Lint all YAML manifests
      - name: Lint manifests
        run: |
          kube-score score ./dev/*.yml
